export type ParLevel = "bls" | "als";

export type ParItem = {
  id: string;
  name: string;
  section: string;
  blsMin: number | null;
  alsMin: number | null;
};

export const PAR_SECTIONS = [
  "PPE / bag",
  "Personal gear",
  "ICS / MCI",
  "C-spine & splints",
  "Assessment",
  "Suction",
  "BLS airway",
  "Laryngoscopy",
  "ALS airway",
  "Ventilation",
  "AED",
  "Monitor / ECG",
  "Oxygen",
  "Wound care",
  "IV / IO",
  "Waste",
  "Linen",
  "Documentation",
  "Medications",
] as const;

export const PAR_ITEMS: ParItem[] = [
  { id: "respiratory-protection", name: "Respiratory Protection", section: "PPE / bag", blsMin: 1, alsMin: 1 },
  { id: "medical-exam-glove", name: "Medical exam gloves (box)", section: "PPE / bag", blsMin: 6, alsMin: 6 },
  { id: "hand-sanitizer", name: "Hand Sanitizer", section: "PPE / bag", blsMin: 1, alsMin: 1 },
  { id: "pocket-mask", name: "Pocket Mask", section: "PPE / bag", blsMin: 1, alsMin: 1 },
  { id: "flashlight", name: "Flashlight", section: "Personal gear", blsMin: 1, alsMin: 1 },
  { id: "stethoscope", name: "Stethoscope", section: "Personal gear", blsMin: 1, alsMin: 1 },
  { id: "trauma-shears", name: "Trauma Shears", section: "Personal gear", blsMin: 1, alsMin: 1 },
  { id: "emergency-response-guidebook", name: "Emergency Response Guidebook", section: "ICS / MCI", blsMin: 1, alsMin: 1 },
  { id: "triage-tags", name: "Triage Tags", section: "ICS / MCI", blsMin: 20, alsMin: 20 },
  { id: "field-operations-guide-ics-420-1", name: "Field Operations Guide (ICS 420-1)", section: "ICS / MCI", blsMin: 1, alsMin: 1 },
  { id: "packet-of-mci-ics-forms", name: "Packet of MCI/ICS Forms", section: "ICS / MCI", blsMin: 1, alsMin: 1 },
  { id: "adjustable-pediatric-c-collar", name: "Adjustable Pediatric C-Collar", section: "C-spine & splints", blsMin: 2, alsMin: 2 },
  { id: "adjustable-adult-c-collar", name: "Adjustable Adult C-Collar", section: "C-spine & splints", blsMin: 2, alsMin: 2 },
  { id: "disposable-head-stabilizer", name: "Disposable Head Stabilizer", section: "C-spine & splints", blsMin: 1, alsMin: 1 },
  { id: "long-spine-board", name: "Long Spine Board", section: "C-spine & splints", blsMin: 1, alsMin: 1 },
  { id: "15-d-ring-spine-board-strap", name: "15\u2019 D-Ring Spine Board Strap", section: "C-spine & splints", blsMin: 2, alsMin: 2 },
  { id: "ked-type-extrication-device", name: "KED Type Extrication Device", section: "C-spine & splints", blsMin: 1, alsMin: 1 },
  { id: "pediatric-stabilization-device", name: "Pediatric Stabilization Device", section: "C-spine & splints", blsMin: 1, alsMin: 1 },
  { id: "arm-splint", name: "Arm Splint", section: "C-spine & splints", blsMin: 2, alsMin: 2 },
  { id: "leg-splint", name: "Leg Splint", section: "C-spine & splints", blsMin: 2, alsMin: 2 },
  { id: "traction-splint-s-with-pediatric-and-adult-capab", name: "Traction Splint(s) with Pediatric and Adult Capabilities", section: "C-spine & splints", blsMin: 1, alsMin: 1 },
  { id: "penlight", name: "Penlight", section: "Assessment", blsMin: 1, alsMin: 1 },
  { id: "trauma-shears-2", name: "Trauma Shears", section: "Assessment", blsMin: 1, alsMin: 1 },
  { id: "stethoscope-2", name: "Stethoscope", section: "Assessment", blsMin: 1, alsMin: 1 },
  { id: "child-bp-cuff", name: "Child BP Cuff", section: "Assessment", blsMin: 1, alsMin: 1 },
  { id: "adult-bp-cuff", name: "Adult BP Cuff", section: "Assessment", blsMin: 1, alsMin: 1 },
  { id: "large-adult-bp-cuff", name: "Large Adult BP Cuff", section: "Assessment", blsMin: 1, alsMin: 1 },
  { id: "length-based-pediatric-resuscitation-tape", name: "Length Based Pediatric Resuscitation Tape", section: "Assessment", blsMin: null, alsMin: 1 },
  { id: "pulse-oximeter-with-pediatric-and-adult-probes-a", name: "Pulse Oximeter with Pediatric and Adult Probes, and Supplies", section: "Assessment", blsMin: null, alsMin: 1 },
  { id: "glucometer-with-lancets-test-strips-and-supplies", name: "Glucometer with Lancets, Test Strips, and Supplies", section: "Assessment", blsMin: null, alsMin: 1 },
  { id: "response-pack-s-bag-s-or-case-s", name: "Response Pack(s), Bag(s), or Case(s)", section: "Assessment", blsMin: 1, alsMin: 1 },
  { id: "battery-powered-portable-suction-unit-with-colle", name: "Battery Powered Portable Suction Unit with Collection Container, Battery/Batteries, and Su", section: "Suction", blsMin: 1, alsMin: 1 },
  { id: "suction-tubing", name: "Suction Tubing", section: "Suction", blsMin: 1, alsMin: 1 },
  { id: "rigid-or-semi-rigid-suction-tip", name: "Rigid or Semi-Rigid Suction Tip", section: "Suction", blsMin: 1, alsMin: 1 },
  { id: "bulb-syringe", name: "Bulb Syringe", section: "Suction", blsMin: 1, alsMin: 1 },
  { id: "suction-catheter-8-fr", name: "Suction Catheter 8 Fr.", section: "Suction", blsMin: 1, alsMin: 1 },
  { id: "suction-catheter-10-fr", name: "Suction Catheter 10 Fr.", section: "Suction", blsMin: 1, alsMin: 1 },
  { id: "suction-catheter-14-fr", name: "Suction Catheter 14 Fr.", section: "Suction", blsMin: 1, alsMin: 1 },
  { id: "size-1-60-mm-oropharyngeal-airway-opa", name: "Size 1 (60 mm) Oropharyngeal Airway (OPA)", section: "BLS airway", blsMin: 1, alsMin: 1 },
  { id: "size-3-80-mm-oropharyngeal-airway-opa", name: "Size 3 (80 mm) Oropharyngeal Airway (OPA)", section: "BLS airway", blsMin: 1, alsMin: 1 },
  { id: "size-5-100-mm-oropharyngeal-airway-opa", name: "Size 5 (100 mm) Oropharyngeal Airway (OPA)", section: "BLS airway", blsMin: 1, alsMin: 1 },
  { id: "20-fr-nasopharyngeal-airway-npa", name: "20 Fr. Nasopharyngeal Airway (NPA)", section: "BLS airway", blsMin: 1, alsMin: 1 },
  { id: "30-fr-nasopharyngeal-airway-npa", name: "30 Fr. Nasopharyngeal Airway (NPA)", section: "BLS airway", blsMin: 1, alsMin: 1 },
  { id: "lubricating-jelly-packets", name: "Lubricating Jelly Packets", section: "BLS airway", blsMin: 2, alsMin: 2 },
  { id: "laryngoscope-handle-with-batteries", name: "Laryngoscope Handle with Batteries", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "extra-batteries", name: "Extra Batteries", section: "Laryngoscopy", blsMin: null, alsMin: 2 },
  { id: "0-straight-blade", name: "0 Straight Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "1-straight-blade", name: "1 Straight Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "2-straight-blade", name: "2 Straight Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "3-straight-blade", name: "3 Straight Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "4-straight-blade", name: "4 Straight Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "2-curved-blade", name: "2 Curved Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "3-curved-blade", name: "3 Curved Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "4-curved-blade", name: "4 Curved Blade", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "extra-bulbs-if-applicable-to-device", name: "Extra Bulbs (if applicable to device)", section: "Laryngoscopy", blsMin: null, alsMin: 2 },
  { id: "pediatric-magill-forceps", name: "Pediatric Magill Forceps", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "adult-magill-forceps", name: "Adult Magill Forceps", section: "Laryngoscopy", blsMin: null, alsMin: 1 },
  { id: "6-mm-cuffed-endotracheal-tube", name: "6 mm Cuffed Endotracheal Tube", section: "ALS airway", blsMin: null, alsMin: 2 },
  { id: "7-mm-cuffed-endotracheal-tube", name: "7 mm Cuffed Endotracheal Tube", section: "ALS airway", blsMin: null, alsMin: 2 },
  { id: "8-mm-cuffed-endotracheal-tube", name: "8 mm Cuffed Endotracheal Tube", section: "ALS airway", blsMin: null, alsMin: 2 },
  { id: "size-3-i-gel-supraglottic-airway-device", name: "Size 3 - i-Gel Supraglottic Airway Device", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "size-4-i-gel-supraglottic-airway-device", name: "Size 4 - i-Gel Supraglottic Airway Device", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "size-5-i-gel-supraglottic-airway-device", name: "Size 5 - i-Gel Supraglottic Airway Device", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "size-10-nasogastric-orogastric-tube", name: "Size 10 - Nasogastric / Orogastric Tube", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "size-14-nasogastric-orogastric-tube", name: "Size 14 - Nasogastric / Orogastric Tube", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "size-16-nasogastric-orogastric-tube", name: "Size 16 - Nasogastric / Orogastric Tube", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "adult-endotracheal-intubation-stylet", name: "Adult Endotracheal Intubation Stylet", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "endotracheal-tube-introducer-stylet-bougie", name: "Endotracheal Tube Introducer Stylet (Bougie)", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "commercial-endotracheal-tube-securing-device", name: "Commercial Endotracheal Tube Securing Device", section: "ALS airway", blsMin: null, alsMin: 1 },
  { id: "neonate-resuscitator-mask", name: "Neonate Resuscitator Mask", section: "Ventilation", blsMin: 1, alsMin: 1 },
  { id: "infant-resuscitator-mask", name: "Infant Resuscitator Mask", section: "Ventilation", blsMin: 1, alsMin: 1 },
  { id: "pediatric-bag-valve-mask-bvm-resuscitator-mask-w", name: "Pediatric Bag Valve Mask (BVM) Resuscitator Mask with O2 Reservoir", section: "Ventilation", blsMin: 1, alsMin: 1 },
  { id: "adult-bag-valve-mask-bvm-resuscitator-mask-with", name: "Adult Bag Valve Mask (BVM) Resuscitator Mask with O2 Reservoir", section: "Ventilation", blsMin: 1, alsMin: 1 },
  { id: "manometer-for-bvm", name: "Manometer for BVM", section: "Ventilation", blsMin: 2, alsMin: 2 },
  { id: "adult-colorimetric-co2-detector", name: "Adult Colorimetric CO2 Detector", section: "Ventilation", blsMin: null, alsMin: 1 },
  { id: "o2-resqtm-cpap-device-with-flow-generator-and-ci", name: "O2-RESQ CPAP Device with Flow Generator and Circuit, one (1) Medium Bi-Trac ED Mask, Hea", section: "Ventilation", blsMin: null, alsMin: 1 },
  { id: "o2-resqtm-large-bi-trac-ed-mask", name: "O2-RESQ Large Bi-Trac ED Mask", section: "Ventilation", blsMin: null, alsMin: 1 },
  { id: "o2-resqtm-12-5-cmh2o-valve", name: "O2-RESQ 12.5 cmH2O Valve", section: "Ventilation", blsMin: null, alsMin: 1 },
  { id: "o2-resqtm-15-cmh2o-valve", name: "O2-RESQ 15 cmH2O Valve", section: "Ventilation", blsMin: null, alsMin: 1 },
  { id: "o2-resqtm-20-cmh2o-valve", name: "O2-RESQ 20 cmH2O Valve", section: "Ventilation", blsMin: null, alsMin: 1 },
  { id: "1-75-2-inch-18-ga-iv-catheter-for-needle-chest-d", name: "1.75-2-inch 18 ga IV Catheter for Needle Chest Decompression", section: "Ventilation", blsMin: null, alsMin: 2 },
  { id: "3-25-inch-14-ga-iv-catheter-for-needle-chest-dec", name: "3.25-inch 14 ga IV Catheter for Needle Chest Decompression", section: "Ventilation", blsMin: null, alsMin: 2 },
  { id: "aed-with-cables-battery-batteries-and-supplies", name: "AED with Cables, Battery/Batteries, and Supplies", section: "AED", blsMin: 1, alsMin: 1 },
  { id: "adult-aed-pads", name: "Adult AED Pads", section: "AED", blsMin: 2, alsMin: 2 },
  { id: "pediatric-aed-pads-or-pediatric-capability-with", name: "Pediatric AED Pads (or Pediatric Capability with Adult Pads)", section: "AED", blsMin: 1, alsMin: 1 },
  { id: "disposable-prep-razor", name: "Disposable Prep Razor", section: "AED", blsMin: 1, alsMin: 1 },
  { id: "waveform-capnography-must-also-have-the-followi", name: "ECG monitor / defibrillator (12-lead, pacing, capnography)", section: "Monitor / ECG", blsMin: null, alsMin: 1 },
  { id: "adult-defibrillation-pad-set", name: "Adult Defibrillation Pad Set", section: "Monitor / ECG", blsMin: null, alsMin: 2 },
  { id: "pediatric-defibrillation-pad-set", name: "Pediatric Defibrillation Pad Set", section: "Monitor / ECG", blsMin: null, alsMin: 1 },
  { id: "adult-ecg-electrodes", name: "Adult ECG Electrodes", section: "Monitor / ECG", blsMin: null, alsMin: 20 },
  { id: "pediatric-ecg-electrodes", name: "Pediatric ECG Electrodes", section: "Monitor / ECG", blsMin: null, alsMin: 8 },
  { id: "disposable-prep-razor-2", name: "Disposable Prep Razor", section: "Monitor / ECG", blsMin: null, alsMin: 1 },
  { id: "tincture-of-benzoin-swabsticks", name: "Tincture of Benzoin Swabsticks", section: "Monitor / ECG", blsMin: null, alsMin: 1 },
  { id: "portable-oxygen-system-with-o2-key-liter-flow-re", name: "Portable Oxygen System with O2 Key, Liter Flow Regulator and Diameter Index Safety System ", section: "Oxygen", blsMin: 1, alsMin: 1 },
  { id: "spare-portable-o2-tank", name: "Spare Portable O2 Tank", section: "Oxygen", blsMin: 1, alsMin: 1 },
  { id: "pediatric-non-rebreather-nrb-o2-mask", name: "Pediatric Non-Rebreather (NRB) O2 Mask", section: "Oxygen", blsMin: 1, alsMin: 1 },
  { id: "adult-non-rebreather-nrb-o2-mask", name: "Adult Non-Rebreather (NRB) O2 Mask", section: "Oxygen", blsMin: 1, alsMin: 1 },
  { id: "pediatric-nasal-cannula", name: "Pediatric Nasal Cannula", section: "Oxygen", blsMin: 1, alsMin: 1 },
  { id: "adult-nasal-cannula", name: "Adult Nasal Cannula", section: "Oxygen", blsMin: 1, alsMin: 1 },
  { id: "4x4-sterile-gauze-sponge", name: "4X4 Sterile Gauze Sponge", section: "Wound care", blsMin: 12, alsMin: 12 },
  { id: "rigid-eye-shield-example", name: "Rigid Eye Shield (Example)", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "abdominal-pad", name: "Abdominal Pad", section: "Wound care", blsMin: 3, alsMin: 3 },
  { id: "trauma-dressing", name: "Trauma Dressing", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "occlusive-dressing", name: "Occlusive Dressing", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "roller-gauze-bandage", name: "Roller Gauze Bandage", section: "Wound care", blsMin: 6, alsMin: 6 },
  { id: "triangular-bandage", name: "Triangular Bandage", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "combat-application-tourniquet-c-a-t", name: "C-A-T tourniquet ", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "transpore-tape", name: "Transpore Tape", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "cloth-tape", name: "Cloth Tape", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "disposable-cold-pack", name: "Disposable Cold Pack", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "sterile-burn-sheet", name: "Sterile Burn Sheet", section: "Wound care", blsMin: 2, alsMin: 2 },
  { id: "1-liter-normal-saline-for-irrigation", name: "1 Liter Normal Saline for Irrigation", section: "Wound care", blsMin: 2, alsMin: 1 },
  { id: "disposable-ob-kit-with-receiving-blanket-and-hea", name: "Disposable OB Kit with Receiving Blanket and Head Cover", section: "Wound care", blsMin: 1, alsMin: 1 },
  { id: "constricting-band", name: "Constricting Band", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "adhesive-band-aid", name: "Adhesive Band-Aid", section: "IV / IO", blsMin: 3, alsMin: 3 },
  { id: "alcohol-swab", name: "Alcohol Swab", section: "IV / IO", blsMin: null, alsMin: 12 },
  { id: "povidone-iodine-swab", name: "Povidone Iodine Swab", section: "IV / IO", blsMin: null, alsMin: 4 },
  { id: "24-ga-iv-catheter", name: "24 ga IV Catheter", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "22-ga-iv-catheter", name: "22 ga IV Catheter", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "20-ga-iv-catheter", name: "20 ga IV Catheter", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "18-ga-iv-catheter", name: "18 ga IV Catheter", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "16-ga-iv-catheter", name: "16 ga IV Catheter", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "14-ga-iv-catheter", name: "14 ga IV Catheter", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "powered-io-device-with-pediatric-capability", name: "Powered IO Device with Pediatric Capability", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "powered-io-device-with-adult-capability", name: "Powered IO Device with Adult Capability", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "handheld-nebulizer-with-mouthpiece-reservoir-and", name: "Handheld Nebulizer with Mouthpiece, Reservoir, and Supply Tubing", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "adult-nebulizer-mask", name: "Adult Nebulizer Mask", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "nebulizer-tee-with-adaptors", name: "Nebulizer Tee with Adaptors", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "mad-nasal-mucosal-atomization-device", name: "MAD Nasal-Mucosal Atomization Device", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "21-ga-x-1-1-5-hypodermic-needle", name: "21 ga X 1 - 1.5\u201d Hypodermic Needle", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "23-ga-x-1-1-5-hypodermic-needle", name: "23 ga X 1 - 1.5\u201d Hypodermic Needle", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "25-ga-x-1-hypodermic-needle", name: "25 ga X 1\u201d Hypodermic Needle", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "1-ml-tb-syringe", name: "1 mL TB Syringe", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "3-ml-syringe", name: "3 mL Syringe", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "5-ml-syringe", name: "5 mL Syringe", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "10-ml-syringe", name: "10 mL Syringe", section: "IV / IO", blsMin: null, alsMin: 3 },
  { id: "20-ml-syringe", name: "20 mL Syringe", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "30-ml-syringe", name: "30 mL Syringe", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "saline-lock-extension-set", name: "Saline Lock Extension Set", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "volume-control-chamber-iv-set", name: "Volume Control Chamber IV Set", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "flow-controller-extension-set-dial-a-flow", name: "Flow Controller Extension set / \u201cDial-a-Flow\u201d", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "10-drop-ml-iv-set", name: "10 drop / mL IV Set", section: "IV / IO", blsMin: null, alsMin: 2 },
  { id: "pressure-infusion-bag", name: "Pressure Infusion Bag", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "narcotic-storage", name: "Narcotic Storage", section: "IV / IO", blsMin: null, alsMin: 1 },
  { id: "portable-sharps-container", name: "Portable Sharps Container", section: "Waste", blsMin: 1, alsMin: 1 },
  { id: "biohazard-bag", name: "Biohazard Bag", section: "Waste", blsMin: 2, alsMin: 2 },
  { id: "emergency-blanket", name: "Emergency Blanket", section: "Linen", blsMin: 2, alsMin: 2 },
  { id: "clipboard", name: "Clipboard", section: "Documentation", blsMin: 1, alsMin: 1 },
  { id: "pen", name: "Pen", section: "Documentation", blsMin: 1, alsMin: 1 },
  { id: "paper-release-forms", name: "Paper Release Forms", section: "Documentation", blsMin: 5, alsMin: 5 },
  { id: "acetaminophen-1000-mg-100-ml-vial-or-iv-premix-b", name: "Acetaminophen 1000 mg/100 mL Vial or IV premix bag", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "adenosine-12-mg-4-ml-prefilled-syringe-or-vial", name: "Adenosine \u2013 12 mg/4 mL Prefilled Syringe or Vial", section: "Medications", blsMin: null, alsMin: 2 },
  { id: "albuterol-0-083-2-5-mg-3-ml-vial", name: "Albuterol 0.083% \u2014 2.5 mg/3 mL Vial", section: "Medications", blsMin: null, alsMin: 3 },
  { id: "amiodarone-150-mg-3-ml-vial", name: "Amiodarone \u2014 150 mg/3 mL Vial", section: "Medications", blsMin: null, alsMin: 3 },
  { id: "aspirin-81-mg-1-tablet-chewable-tablet-in-packet", name: "Aspirin 81 mg chewable (20-tab bottle)", section: "Medications", blsMin: null, alsMin: 8 },
  { id: "atropine-1-mg-10-ml-prefilled-syringe", name: "Atropine \u2014 1 mg/10 mL Prefilled Syringe", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "atropine-8-mg-20-ml-vial", name: "Atropine \u2014 8 mg/20 mL Vial", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "calcium-chloride-10-1-g-10-ml-prefilled-syringe", name: "Calcium Chloride 10% \u2014 1 g/10 mL Prefilled Syringe", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "dextrose-10-25-g-250-ml-iv-bag", name: "Dextrose 10% \u2014 25 g/250 mL IV Bag", section: "Medications", blsMin: null, alsMin: 2 },
  { id: "diphenhydramine-50-mg-1-ml-vial-or-carpuject", name: "Diphenhydramine \u2014 50 mg/1 mL Vial or Carpuject", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "epinephrine-1-1-000-1-mg-1-ml-vial-or-ampule", name: "Epinephrine 1:1,000 1 mg", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "epi-1-10-000-1-mg-10-ml-prefilled-syringe", name: "Epinephrine 1:10,000 1 mg PFS", section: "Medications", blsMin: null, alsMin: 3 },
  { id: "glucagon-glucagen-1-mg-1-ml-vial-of-glucagon-pow", name: "Glucagon 1 mg", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "glucose-gel-1-container", name: "Glucose gel", section: "Medications", blsMin: 1, alsMin: 1 },
  { id: "ipratropium-br-0-5-mg-2-5-ml-vial", name: "Ipratropium Br.\u2014 0.5 mg/2.5 mL Vial", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "lidocaine-2-100-mg-5-ml-prefilled-syringe", name: "Lidocaine 2% \u2014 100 mg /5 mL Prefilled Syringe", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "ketorolac-toradol-30-mg-ml-vial", name: "Ketorolac (Toradol) \u2013 30 mg/mL Vial", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "magnesium-sulfate-5g-10ml-prefilled-syringe-or-v", name: "Magnesium Sulfate - 5g/10mL Prefilled Syringe or Vial", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "naloxone-2-mg-2-ml-prefilled-syringe-or-vial", name: "Naloxone 2 mg/2 mL", section: "Medications", blsMin: null, alsMin: 4 },
  { id: "nitroglycerin-0-4-mg-1-dose-multi-dose-spray-or", name: "Nitroglycerin 0.4 mg spray/tabs", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "nitro-paste-2-1-g-1-inch-packet-with-paper-appli", name: "Nitro. Paste 2% \u2014 1 g/1 Inch, Packet with Paper Applicators", section: "Medications", blsMin: null, alsMin: 2 },
  { id: "normal-saline-0-9-1000-ml-iv-bag", name: "NS 1000 mL IV Bag", section: "Medications", blsMin: null, alsMin: 2 },
  { id: "normal-saline-0-9-50-ml-iv-bag", name: "NS 50 mL IV Bag", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "normal-saline-0-9-10-ml-prefilled-syringe-or-via", name: "NS 10 mL Prefilled Syringe or Vial", section: "Medications", blsMin: null, alsMin: 2 },
  { id: "ondansetron-4-mg-2-ml-prefilled-syringe-or-vial", name: "Ondansetron \u2014 4 mg/2 mL, Prefilled Syringe or Vial", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "ondansetron-4-mg-1-oral-disintegrating-tablet-od", name: "Ondansetron \u2014 4 mg/1 Oral Disintegrating Tablet (ODT)", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "sodium-bicarbonate-8-4-50-meq-50-ml-prefilled-sy", name: "Sodium Bicarbonate 8.4% - 50 mEq/50 mL Prefilled Syringe or Vial", section: "Medications", blsMin: null, alsMin: 1 },
  { id: "tranexamic-acid-1-gram-10-ml-vial", name: "Tranexamic Acid 1 gram/10 mL Vial", section: "Medications", blsMin: null, alsMin: 2 },
  { id: "midazolam-5-mg-1-ml-ampule-vial-or-carpuject", name: "Midazolam \u2014 5 mg/1 mL Ampule, Vial or Carpuject", section: "Medications", blsMin: null, alsMin: 2 },
];

export function protocolMin(item: ParItem, level: ParLevel): number | null {
  return level === "bls" ? item.blsMin : item.alsMin;
}

/** Station cabinet min. 3303 is one ALS unit; CFD staffs 2 daily, sometimes a 3rd. */
const CAPITAL = new Set([
  "long-spine-board",
  "ked-type-extrication-device",
  "pediatric-stabilization-device",
  "traction-splint-s-with-pediatric-and-adult-capab",
  "length-based-pediatric-resuscitation-tape",
  "pulse-oximeter-with-pediatric-and-adult-probes-a",
  "glucometer-with-lancets-test-strips-and-supplies",
  "response-pack-s-bag-s-or-case-s",
  "battery-powered-portable-suction-unit-with-colle",
  "laryngoscope-handle-with-batteries",
  "pediatric-magill-forceps",
  "adult-magill-forceps",
  "o2-resqtm-cpap-device-with-flow-generator-and-ci",
  "aed-with-cables-battery-batteries-and-supplies",
  "waveform-capnography-must-also-have-the-followi",
  "portable-oxygen-system-with-o2-key-liter-flow-re",
  "powered-io-device-with-pediatric-capability",
  "powered-io-device-with-adult-capability",
  "narcotic-storage",
  "clipboard",
  "emergency-response-guidebook",
  "field-operations-guide-ics-420-1",
  "pressure-infusion-bag",
]);

const SPARE3 = new Set([
  "flashlight",
  "stethoscope",
  "trauma-shears",
  "trauma-shears-2",
  "stethoscope-2",
  "penlight",
  "child-bp-cuff",
  "adult-bp-cuff",
  "large-adult-bp-cuff",
  "pocket-mask",
  "neonate-resuscitator-mask",
  "infant-resuscitator-mask",
  "pediatric-bag-valve-mask-bvm-resuscitator-mask-w",
  "adult-bag-valve-mask-bvm-resuscitator-mask-with",
  "manometer-for-bvm",
]);

const RARE = new Set([
  "acetaminophen-1000-mg-100-ml-vial-or-iv-premix-b",
  "adenosine-12-mg-4-ml-prefilled-syringe-or-vial",
  "amiodarone-150-mg-3-ml-vial",
  "atropine-1-mg-10-ml-prefilled-syringe",
  "atropine-8-mg-20-ml-vial",
  "calcium-chloride-10-1-g-10-ml-prefilled-syringe",
  "glucagon-glucagen-1-mg-1-ml-vial-of-glucagon-pow",
  "lidocaine-2-100-mg-5-ml-prefilled-syringe",
  "ketorolac-toradol-30-mg-ml-vial",
  "magnesium-sulfate-5g-10ml-prefilled-syringe-or-v",
  "sodium-bicarbonate-8-4-50-meq-50-ml-prefilled-sy",
  "tranexamic-acid-1-gram-10-ml-vial",
  "midazolam-5-mg-1-ml-ampule-vial-or-carpuject",
  "ipratropium-br-0-5-mg-2-5-ml-vial",
  "nitro-paste-2-1-g-1-inch-packet-with-paper-appli",
  "normal-saline-0-9-50-ml-iv-bag",
  "6-mm-cuffed-endotracheal-tube",
  "7-mm-cuffed-endotracheal-tube",
  "8-mm-cuffed-endotracheal-tube",
  "size-10-nasogastric-orogastric-tube",
  "size-14-nasogastric-orogastric-tube",
  "size-16-nasogastric-orogastric-tube",
  "0-straight-blade",
  "1-straight-blade",
  "2-straight-blade",
  "3-straight-blade",
  "4-straight-blade",
  "2-curved-blade",
  "3-curved-blade",
  "4-curved-blade",
  "extra-batteries",
  "extra-bulbs-if-applicable-to-device",
  "flow-controller-extension-set-dial-a-flow",
  "volume-control-chamber-iv-set",
  "24-ga-iv-catheter",
  "16-ga-iv-catheter",
  "14-ga-iv-catheter",
  "20-ml-syringe",
  "rigid-eye-shield-example",
  "disposable-ob-kit-with-receiving-blanket-and-hea",
  "pediatric-defibrillation-pad-set",
  "pediatric-ecg-electrodes",
  "pediatric-aed-pads-or-pediatric-capability-with",
]);

const BURN = new Set([
  "4x4-sterile-gauze-sponge",
  "roller-gauze-bandage",
  "trauma-dressing",
  "occlusive-dressing",
  "abdominal-pad",
  "adhesive-band-aid",
  "alcohol-swab",
  "18-ga-iv-catheter",
  "20-ga-iv-catheter",
  "22-ga-iv-catheter",
  "10-ml-syringe",
  "normal-saline-0-9-10-ml-prefilled-syringe-or-via",
  "handheld-nebulizer-with-mouthpiece-reservoir-and",
  "pediatric-non-rebreather-nrb-o2-mask",
  "adult-non-rebreather-nrb-o2-mask",
  "pediatric-nasal-cannula",
  "adult-nasal-cannula",
  "adult-ecg-electrodes",
  "albuterol-0-083-2-5-mg-3-ml-vial",
  "dextrose-10-25-g-250-ml-iv-bag",
  "epi-1-10-000-1-mg-10-ml-prefilled-syringe",
  "naloxone-2-mg-2-ml-prefilled-syringe-or-vial",
  "glucose-gel-1-container",
  "ondansetron-4-mg-2-ml-prefilled-syringe-or-vial",
  "ondansetron-4-mg-1-oral-disintegrating-tablet-od",
  "normal-saline-0-9-1000-ml-iv-bag",
  "epinephrine-1-1-000-1-mg-1-ml-vial-or-ampule",
  "diphenhydramine-50-mg-1-ml-vial-or-carpuject",
  "suction-tubing",
  "rigid-or-semi-rigid-suction-tip",
  "suction-catheter-8-fr",
  "suction-catheter-10-fr",
  "suction-catheter-14-fr",
  "lubricating-jelly-packets",
  "paper-release-forms",
  "disposable-cold-pack",
  "biohazard-bag",
  "emergency-blanket",
  "constricting-band",
  "adult-defibrillation-pad-set",
  "adult-aed-pads",
  "10-drop-ml-iv-set",
  "saline-lock-extension-set",
  "mad-nasal-mucosal-atomization-device",
  "size-4-i-gel-supraglottic-airway-device",
  "size-5-i-gel-supraglottic-airway-device",
]);

export function stationMin(item: ParItem, level: ParLevel): number | null {
  const unit = protocolMin(item, level);
  if (unit == null) return null;
  if (item.id.startsWith("fac-")) return unit;
  if (item.id === "aspirin-81-mg-1-tablet-chewable-tablet-in-packet") return 2;
  if (item.id === "medical-exam-glove") return 3;
  if (item.id === "nitroglycerin-0-4-mg-1-dose-multi-dose-spray-or") return 3;
  if (item.id === "spare-portable-o2-tank") return 4;
  if (item.id === "respiratory-protection") return 10;
  if (CAPITAL.has(item.id)) return 1;
  if (SPARE3.has(item.id)) return 3;
  if (RARE.has(item.id)) return unit * 3;
  if (BURN.has(item.id)) return unit * 5;
  return unit * 4;
}

export function defaultQty(item: ParItem): number {
  if (item.id.startsWith("fac-")) return 0;
  return stationMin(item, "als") ?? stationMin(item, "bls") ?? 0;
}


