/** NWCG 6 Minutes for Safety — 2026 daily calendar from nwcg.gov. Key is MM-DD. */
export type SixMinutesTopic = { title: string; href: string };

const CALENDAR: Record<string, readonly [string, string]> = {
  "01-01": ["Aircraft and Pilot Carding", "/6mfs/aviation/aircraft-and-pilot-carding"],
  "01-02": ["Avoiding Fuel Geysering", "/6mfs/misc-fireline-hazards/avoiding-fuel-geysering"],
  "01-03": ["AAR Part 1", "/6mfs/fire-communication/after-action-review-aar-part-1"],
  "01-04": ["AAR Part 2", "/6mfs/fire-communication/after-action-review-aar-part-2"],
  "01-05": ["Hypothermia", "/6mfs/firefighter-health-first-aid/hypothermia"],
  "01-06": ["Adaptability/Flexibility During High-Tempo Periods", "/6mfs/leadership/adaptabilityflexibility-during-high-tempo-periods"],
  "01-07": ["10 Standard Firefighting Orders", "/6mfs/operational-engagement/10-standard-firefighting-orders"],
  "01-08": ["Base All Actions on Current and Expected Fire Behavior", "/6mfs/weather-fire-behavior/base-all-actions-current-and-expected-fire-behavior"],
  "01-09": ["Aviation Watch Outs", "/6mfs/aviation/aviation-watch-outs"],
  "01-10": ["Aviation Communication", "/6mfs/aviation/aviation-communication"],
  "01-11": ["Firefighter Nutrition", "/6mfs/firefighter-health-first-aid/firefighter-nutrition"],
  "01-12": ["Attempting a Frontal Assault on a Fire", "/6mfs/operational-engagement/attempting-frontal-assault-fire"],
  "01-13": ["Common Denominators of Fire Behavior on Tragedy Fires", "/6mfs/weather-fire-behavior/common-denominators-of-fire-behavior-tragedy-fires"],
  "01-14": ["Propane Tank Hazards", "/6mfs/misc-fireline-hazards/propane-tank-hazards"],
  "01-15": ["Building Fireline Downhill With Fire Below", "/6mfs/operational-engagement/building-fireline-downhill-fire-below"],
  "01-16": ["Fatigue & Stress", "/6mfs/firefighter-health-first-aid/fatigue-stress"],
  "01-17": ["Dozer/Plow Operations", "/6mfs/vehicles-roads/dozerplow-operations"],
  "01-18": ["Ash Pit Hazards", "/6mfs/misc-fireline-hazards/ash-pit-hazards"],
  "01-19": ["Constructing Line Without a Safe Anchor Point", "/6mfs/operational-engagement/constructing-line-without-safe-anchor-point"],
  "01-20": ["Downhill Fireline Construction Checklist", "/6mfs/operational-engagement/downhill-fireline-construction-checklist"],
  "01-21": ["Communication", "/6mfs/fire-communication/communications-lces"],
  "01-22": ["Inattentive Blindness", "/6mfs/leadership/inattentive-blindness"],
  "01-23": ["Entrapment Avoidance", "/6mfs/operational-engagement/entrapment-avoidance"],
  "01-24": ["Escape Routes 1", "/6mfs/operational-engagement/escape-routes-1"],
  "01-25": ["Bias for Action", "/6mfs/leadership/bias-for-action"],
  "01-26": ["Leading Up", "/6mfs/leadership/leading"],
  "01-27": ["Effects of Smoke Exposure", "/6mfs/firefighter-health-first-aid/effects-of-smoke-exposure"],
  "01-28": ["Contagious Diseases", "/6mfs/firefighter-health-first-aid/contagious-diseases"],
  "01-29": ["Aviation Mishap Response", "/6mfs/aviation/nwcg-aviation-mishap-response-guide-and-checklist-pms-503"],
  "01-30": ["Falling Snags", "/6mfs/felling-safety/falling-snags"],
  "01-31": ["Chainsaw Safety", "/6mfs/felling-safety/chainsaw-safety"],
  "02-01": ["Dirty Nomex®", "/6mfs/firefighter-health-first-aid/dirty-nomexr"],
  "02-02": ["Instructions and Assignments Not Clear", "/6mfs/fire-communication/instructions-and-assignments-not-clear"],
  "02-03": ["Driving Safety", "/6mfs/vehicles-roads/driving-safety"],
  "02-04": ["Extended Attack", "/6mfs/operational-engagement/extended-attack"],
  "02-05": ["Building the Team", "/6mfs/leadership/building-team"],
  "02-06": ["Fight Fire Aggressively But Provide for Safety First", "/6mfs/operational-engagement/fight-fire-aggressively-having-provided-for-safety-first"],
  "02-07": ["Aviation Watch Outs", "/6mfs/aviation/aviation-watch-outs"],
  "02-08": ["Hazard Tree - No Work Zones", "/6mfs/felling-safety/hazard-tree-no-work-zones"],
  "02-09": ["Frequent Spot Fires Across the Line", "/6mfs/weather-fire-behavior/frequent-spot-fires-across-line"],
  "02-10": ["Fuel Handling", "/6mfs/misc-fireline-hazards/fuel-handling"],
  "02-11": ["Fire Not Scouted and Sized Up", "/6mfs/operational-engagement/fire-not-scouted-and-sized"],
  "02-12": ["ATV-Safety", "/6mfs/vehicles-roads/atv-safety"],
  "02-13": ["My Safety", "/6mfs/leadership/my-safety"],
  "02-14": ["Fire Shelter Deployment", "/6mfs/operational-engagement/fire-shelter-deployment"],
  "02-15": ["Fire Shelter Deployment Site Selection", "/6mfs/operational-engagement/fire-shelter-deployment-site-selection"],
  "02-16": ["Fire Shelter Stigma", "/6mfs/operational-engagement/fire-shelter-stigma"],
  "02-17": ["Command Presence", "/6mfs/leadership/command-presence"],
  "02-18": ["Helicopter Landing Area Safety", "/6mfs/aviation/helicopter-landing-area-safety"],
  "02-19": ["Helicopter Landing Zone Selection", "/6mfs/aviation/helicopter-landing-zone-selection"],
  "02-20": ["Escape Routes 1", "/6mfs/operational-engagement/escape-routes-1"],
  "02-21": ["Escape Routes 2", "/6mfs/operational-engagement/escape-routes-2"],
  "02-22": ["Escape Routes 3", "/6mfs/operational-engagement/escape-routes-3"],
  "02-23": ["Hydration", "/6mfs/firefighter-health-first-aid/hydration"],
  "02-24": ["Medical Incident Report", "/6mfs/fire-communication/medical-incident-report"],
  "02-25": ["Hazard Mitigation Through Risk Management", "/6mfs/operational-engagement/hazard-mitigation-through-risk-management"],
  "02-26": ["Hazard Tree - Risk Management", "/6mfs/felling-safety/hazard-tree-risk-management"],
  "02-27": ["Hazmat Incident Operations", "/6mfs/misc-fireline-hazards/hazmat-incident-operations"],
  "02-28": ["NFDRS PocketCards", "/6mfs/weather-fire-behavior/nfdrs-pocketcards"],
  "03-01": ["Developing a Learning Organization", "/6mfs/leadership/developing-learning-organization"],
  "03-02": ["Managing Vehicle Traffic in Smoke", "/6mfs/vehicles-roads/managing-vehicle-traffic-in-smoke"],
  "03-03": ["Proper Use of Trigger Points", "/6mfs/weather-fire-behavior/proper-use-of-trigger-points"],
  "03-04": ["Leader's Intent", "/6mfs/leadership/leaders-intent"],
  "03-05": ["No Communication Link", "/6mfs/fire-communication/no-communication-link-crewmembers-or-supervisor"],
  "03-06": ["In Country Not Seen in Daylight", "/6mfs/operational-engagement/in-country-not-seen-in-daylight"],
  "03-07": ["Initial Attack Sizeup/Safety", "/6mfs/operational-engagement/initial-attack-sizeupsafety"],
  "03-08": ["Lookouts (LCES)", "/6mfs/operational-engagement/lookouts-lces"],
  "03-09": ["Emergencies on the Ramp", "/6mfs/aviation/emergencies-on-the-ramp"],
  "03-10": ["On a Hillside Where Rolling Material Can Ignite Fuel Below", "/6mfs/operational-engagement/hillside-where-rolling-material-can-ignite-fuel-below"],
  "03-11": ["Helicopter Performance", "/6mfs/aviation/helicopter-performance"],
  "03-12": ["Refusing Risk", "/6mfs/operational-engagement/refusing-risk"],
  "03-13": ["Mine Features and Hazards", "/6mfs/misc-fireline-hazards/mine-features-and-hazards"],
  "03-14": ["Noise Exposure Safety", "/6mfs/firefighter-health-and-first-aid-miscellaneous-fireline-hazards/noise-exposure-safety"],
  "03-15": ["Safety Zone Research", "/6mfs/operational-engagement/safety-zone-research"],
  "03-16": ["Safety Zones 1 (LCES)", "/6mfs/operational-engagement/safety-zones-1-lces"],
  "03-17": ["Safety Zones 2 (LCES)", "/6mfs/operational-engagement/safety-zones-2-lces"],
  "03-18": ["Spot Weather Forecast", "/6mfs/weather-fire-behavior/spot-weather-forecast"],
  "03-19": ["Subjective vs. Objective Hazards", "/6mfs/operational-engagement/subjective-vs-objective-hazards"],
  "03-20": ["Taking a Nap Near the Fireline", "/6mfs/operational-engagement/taking-nap-near-fireline"],
  "03-21": ["Thunderstorm Safety", "/6mfs/weather-fire-behavior/thunderstorm-safety"],
  "03-22": ["Hazmat Incident Operations", "/6mfs/misc-fireline-hazards/hazmat-incident-operations"],
  "03-23": ["Hazard Tree Felling - Hang-ups", "/6mfs/felling-safety/hazard-tree-felling-hang-ups"],
  "03-24": ["Operational Briefings", "/6mfs/fire-communication/operational-briefings"],
  "03-25": ["Terrain and Fuels Make Escape Difficult", "/6mfs/operational-engagement/terrain-and-fuels-make-escape-safety-zones-difficult"],
  "03-26": ["Five Communication Responsibilities", "/6mfs/leadership/five-communication-responsibilities"],
  "03-27": ["Hazard Tree Felling Safety Tips", "/6mfs/felling-safety/hazard-tree-felling-safety-tips"],
  "03-28": ["Powerline Safety", "/6mfs/misc-fireline-hazards/power-line-safety"],
  "03-29": ["Transfer of Command", "/6mfs/operational-engagement/transfer-of-command"],
  "03-30": ["UAS Incursions", "/6mfs/aviation/uas-incursions"],
  "03-31": ["Parking Safely on Slopes", "/6mfs/vehicles-roads/parking-safely-slopes"],
  "04-01": ["Serious Injury Procedures", "/6mfs/firefighter-health-first-aid/serious-injury-procedures"],
  "04-02": ["Unfamiliar with Weather and Local Factors", "/6mfs/weather-fire-behavior/unfamiliar-weather-and-local-factors"],
  "04-03": ["Unburned Fuel Between You and the Fire", "/6mfs/operational-engagement/unburned-fuel-between-you-and-fire"],
  "04-04": ["Responding to Vehicle Fires", "/6mfs/vehicles-roads/responding-vehicle-fires"],
  "04-05": ["Retardant & Water Drop Safety", "/6mfs/aviation/retardant-and-water-drop-safety"],
  "04-06": ["Hazard Tree Identification", "/6mfs/felling-safety/hazard-tree-identification"],
  "04-07": ["SAFENETs", "/6mfs/fire-communication/safenet"],
  "04-08": ["SAFECOMs", "/6mfs/aviation/safecoms"],
  "04-09": ["Leader's Intent", "/6mfs/leadership/leaders-intent"],
  "04-10": ["Propane Tank Hazards", "/6mfs/misc-fireline-hazards/propane-tank-hazards"],
  "04-11": ["Base All Actions on Current and Expected Fire Behavior", "/6mfs/weather-fire-behavior/base-all-actions-current-and-expected-fire-behavior"],
  "04-12": ["Uninformed on Strategy, Tactics or Hazards", "/6mfs/operational-engagement/uninformed-strategy-tactics-or-hazards"],
  "04-13": ["Working with Helicopter Drops", "/6mfs/aviation/working-helicopter-drops"],
  "04-14": ["Wildland/Urban Interface-Structure Protection", "/6mfs/operational-engagement/wildland-urban-interface-structure-protection"],
  "04-15": ["Wildland/Urban Interface Watch Outs", "/6mfs/operational-engagement/wildland-urban-interface-watch-outs"],
  "04-16": ["SAFECOMs", "/6mfs/aviation/safecoms"],
  "04-17": ["Hazard Tree Secure Felling Area", "/6mfs/felling-safety/hazard-tree-secure-felling-area"],
  "04-18": ["10 Standard Firefighting Orders", "/6mfs/operational-engagement/10-standard-firefighting-orders"],
  "04-19": ["Attempting a Frontal Assault on a Fire", "/6mfs/operational-engagement/attempting-frontal-assault-fire"],
  "04-20": ["Leadership Environment", "/6mfs/leadership/leadership-environment"],
  "04-21": ["Unexploded Ordnance Safety", "/6mfs/misc-fireline-hazards/unexploded-ordnance-safety"],
  "04-22": ["Building Fireline Downhill With Fire Below", "/6mfs/operational-engagement/building-fireline-downhill-fire-below"],
  "04-23": ["Roadside Incident Response", "/6mfs/vehicles-roads/roadside-incident-response"],
  "04-24": ["AAR Part 1", "/6mfs/fire-communication/after-action-review-aar-part-1"],
  "04-25": ["AAR Part 2", "/6mfs/fire-communication/after-action-review-aar-part-2"],
  "04-26": ["Working with Helicopter Drops", "/6mfs/aviation/working-helicopter-drops"],
  "04-27": ["Common Denominators of Fire Behavior on Tragedy Fires", "/6mfs/weather-fire-behavior/common-denominators-of-fire-behavior-tragedy-fires"],
  "04-28": ["Hazard Tree - Situational Awareness", "/6mfs/felling-safety/hazard-tree-situational-awareness"],
  "04-29": ["Take 5@2 PPE", "/6mfs/firefighter-health-first-aid/take-52-ppe"],
  "04-30": ["Constructing Line Without a Safe Anchor Point", "/6mfs/operational-engagement/constructing-line-without-safe-anchor-point"],
  "05-01": ["Leading Up", "/6mfs/leadership/leading"],
  "05-02": ["Vehicle Entrapment", "/6mfs/vehicles-roads/vehicle-entrapment"],
  "05-03": ["Aircraft and Pilot Carding", "/6mfs/aviation/aircraft-and-pilot-carding"],
  "05-04": ["Valley Fever", "/6mfs/firefighter-health-first-aid/valley-fever"],
  "05-05": ["Communication", "/6mfs/fire-communication/communications-lces"],
  "05-06": ["Extreme Fire Behavior – I", "/6mfs/weather-fire-behavior/extreme-fire-behavior-i"],
  "05-07": ["Extreme Fire Behavior – II", "/6mfs/weather-fire-behavior/extreme-fire-behavior-ii"],
  "05-08": ["Chainsaw Safety", "/6mfs/felling-safety/chainsaw-safety"],
  "05-09": ["Bees and Wasps", "/6mfs/firefighter-health-first-aid/bees-and-wasps"],
  "05-10": ["Ash Pit Hazards", "/6mfs/misc-fireline-hazards/ash-pit-hazards"],
  "05-11": ["Driving Safety", "/6mfs/vehicles-roads/driving-safety"],
  "05-12": ["Downhill Fireline Construction Checklist", "/6mfs/operational-engagement/downhill-fireline-construction-checklist"],
  "05-13": ["Hot Loading", "/6mfs/airtankers/hot-loading"],
  "05-14": ["Entrapment Avoidance", "/6mfs/operational-engagement/entrapment-avoidance"],
  "05-15": ["Fire Not Scouted and Sized Up", "/6mfs/operational-engagement/fire-not-scouted-and-sized"],
  "05-16": ["Burn Protocols", "/6mfs/firefighter-health-first-aid/burn-protocols"],
  "05-17": ["Making Sound and Timely Decisions", "/6mfs/leadership/making-sound-and-timely-decisions"],
  "05-18": ["Falling Snags", "/6mfs/felling-safety/falling-snags"],
  "05-19": ["Extended Attack", "/6mfs/operational-engagement/extended-attack"],
  "05-20": ["Fight Fire Aggressively But Provide for Safety First", "/6mfs/operational-engagement/fight-fire-aggressively-having-provided-for-safety-first"],
  "05-21": ["Avoiding Fuel Geysering", "/6mfs/misc-fireline-hazards/avoiding-fuel-geysering"],
  "05-22": ["Instructions and Assignments Not Clear", "/6mfs/fire-communication/instructions-and-assignments-not-clear"],
  "05-23": ["Escape Routes 1", "/6mfs/operational-engagement/escape-routes-1"],
  "05-24": ["Escape Routes 2", "/6mfs/operational-engagement/escape-routes-2"],
  "05-25": ["Escape Routes 3", "/6mfs/operational-engagement/escape-routes-3"],
  "05-26": ["Effects of Smoke Exposure", "/6mfs/firefighter-health-first-aid/effects-of-smoke-exposure"],
  "05-27": ["Managing Vehicle Traffic in Smoke", "/6mfs/vehicles-roads/managing-vehicle-traffic-in-smoke"],
  "05-28": ["Fire Shelter Deployment", "/6mfs/operational-engagement/fire-shelter-deployment"],
  "05-29": ["Aviation Mishap Response", "/6mfs/aviation/nwcg-aviation-mishap-response-guide-and-checklist-pms-503"],
  "05-30": ["Hazard Tree - No Work Zones", "/6mfs/felling-safety/hazard-tree-no-work-zones"],
  "05-31": ["NFDRS PocketCards", "/6mfs/weather-fire-behavior/nfdrs-pocketcards"],
  "06-01": ["Mackenzie Fire Shelter Deployment – June 1, 1994", "/6mfs/day-in-history/mackenzie-fire-shelter-deployment-june-1-1994"],
  "06-02": ["Simultaneous Loading and Fueling (SL+F) Airtankers", "/6mfs/airtankers/simultaneous-loading-and-fueling-slf-airtankers"],
  "06-03": ["Fuel Handling", "/6mfs/misc-fireline-hazards/fuel-handling"],
  "06-04": ["Heat Disorders", "/6mfs/firefighter-health-first-aid/heat-disorders"],
  "06-05": ["Base All Actions on Current and Expected Fire Behavior", "/6mfs/weather-fire-behavior/base-all-actions-current-and-expected-fire-behavior"],
  "06-06": ["Aviation Watch Outs", "/6mfs/aviation/aviation-watch-outs"],
  "06-07": ["Carcinogen Exposure Risk", "/6mfs/firefighter-health-first-aid/carcinogen-exposure-risk"],
  "06-08": ["Hazard Tree - Risk Management", "/6mfs/felling-safety/hazard-tree-risk-management"],
  "06-09": ["Firefighter Nutrition", "/6mfs/firefighter-health-first-aid/firefighter-nutrition"],
  "06-10": ["Hazard Mitigation Through Risk Management", "/6mfs/operational-engagement/hazard-mitigation-through-risk-management"],
  "06-11": ["In Country Not Seen in Daylight", "/6mfs/operational-engagement/in-country-not-seen-in-daylight"],
  "06-12": ["Initial Attack Sizeup/Safety", "/6mfs/operational-engagement/initial-attack-sizeupsafety"],
  "06-13": ["PPE – Helmet Inspection and Care", "/6mfs/firefighter-health-first-aid/personal-protective-equipment-helmet-inspection-and-care"],
  "06-14": ["Helicopter Landing Area Safety", "/6mfs/aviation/helicopter-landing-area-safety"],
  "06-15": ["Helicopter Landing Zone Selection", "/6mfs/aviation/helicopter-landing-zone-selection"],
  "06-16": ["Operational Tempo", "/6mfs/leadership/operational-tempo"],
  "06-17": ["Origin of the 10 and 18's", "/6mfs/day-in-history/origin-of-10-and-18-june-17-1957"],
  "06-18": ["No Communication Link", "/6mfs/fire-communication/no-communication-link-crewmembers-or-supervisor"],
  "06-19": ["Hazard Tree Felling - Hang-ups", "/6mfs/felling-safety/hazard-tree-felling-hang-ups"],
  "06-20": ["Lookouts (LCES)", "/6mfs/operational-engagement/lookouts-lces"],
  "06-21": ["Heat Disorders", "/6mfs/firefighter-health-first-aid/heat-disorders"],
  "06-22": ["Safety Zones 1 (LCES)", "/6mfs/operational-engagement/safety-zones-1-lces"],
  "06-23": ["Safety Zones 2 (LCES)", "/6mfs/operational-engagement/safety-zones-2-lces"],
  "06-24": ["Spot Weather Forecast", "/6mfs/weather-fire-behavior/spot-weather-forecast"],
  "06-25": ["Valley Fever", "/6mfs/firefighter-health-first-aid/valley-fever"],
  "06-26": ["Dude Fire", "/6mfs/day-in-history/dude-fire-arizona-june-26-1990"],
  "06-27": ["LCES", "/6mfs/day-in-history/lces-june-26-1990"],
  "06-28": ["Helicopter Performance", "/6mfs/aviation/helicopter-performance"],
  "06-29": ["Peer Accountability", "/6mfs/leadership/peer-accountability"],
  "06-30": ["2026 WOR: Fire Season 2016", "/6mfs/week-of-remembrance/2026-week-of-remembrance-day-1"],
  "07-01": ["2026 WOR: Mulholland Fire Struck by Rock Fatality – Shawna Lynn Jones", "/6mfs/week-of-remembrance/2026-week-of-remembrance-day-2"],
  "07-02": ["2026 WOR: Denio Engine Rollover – Jacob O’Malley and Will Hawkins", "/6mfs/week-of-remembrance/2026-week-of-remembrance-day-3"],
  "07-03": ["2026 WOR: Soberanes Fire Dozer Fatality – Robert Oliver Reagan III", "/6mfs/week-of-remembrance/2026-week-of-remembrance-day-4"],
  "07-04": ["2026 WOR: Strawberry Fire Tree Strike Fatality – Justin Beebe", "/6mfs/week-of-remembrance/2026-week-of-remembrance-day-5"],
  "07-05": ["2026 WOR: Redmond Smokejumper Fatality – Ray Rubio", "/6mfs/week-of-remembrance/2026-week-of-remembrance-day-6"],
  "07-06": ["2026 WOR: June 30 to July 6, 2026 Fire Season 2016", "/6mfs/week-of-remembrance/2026-week-of-remembrance-day-7"],
  "07-07": ["Hazard Tree Felling Safety Tips", "/6mfs/felling-safety/hazard-tree-felling-safety-tips"],
  "07-08": ["Situational Awareness", "/6mfs/leadership/situational-awareness"],
  "07-09": ["Valley Fever", "/6mfs/firefighter-health-first-aid/valley-fever"],
  "07-10": ["Thirtymile Fire", "/6mfs/day-in-history/thirtymile-fire-washington-july-10-2001"],
  "07-11": ["Powerline Safety", "/6mfs/misc-fireline-hazards/power-line-safety"],
  "07-12": ["Operational Briefings", "/6mfs/fire-communication/operational-briefings"],
  "07-13": ["Heat Stress", "/6mfs/firefighter-health-first-aid/heat-stress"],
  "07-14": ["Hydration", "/6mfs/firefighter-health-first-aid/hydration"],
  "07-15": ["Active Shooter – How to Respond", "/6mfs/firefighter-health-first-aid/active-shooter-how-respond"],
  "07-16": ["Firefighter Nutrition", "/6mfs/firefighter-health-first-aid/firefighter-nutrition"],
  "07-17": ["Battlement Creek Fire", "/6mfs/day-in-history/battlement-creek-fire-colorado-july-17-1976"],
  "07-18": ["Little Venus Fire (Wyoming)", "/6mfs/day-in-history/little-venus-fire-wyoming-july-18-2006"],
  "07-19": ["Responding to Vehicle Fires", "/6mfs/vehicles-roads/responding-vehicle-fires"],
  "07-20": ["UAS Incursions", "/6mfs/aviation/uas-incursions"],
  "07-21": ["Hazard Tree Identification", "/6mfs/felling-safety/hazard-tree-identification"],
  "07-22": ["Cramer Fire", "/6mfs/day-in-history/cramer-fire-idaho-july-22-2003"],
  "07-23": ["Elk Fire - Helicopter Accident", "/6mfs/day-in-history/elk-complex-helicopter-accident-california-july-23-2007"],
  "07-24": ["NFDRS PocketCards", "/6mfs/weather-fire-behavior/nfdrs-pocketcards"],
  "07-25": ["Dutch Creek Incident", "/6mfs/day-in-history/dutch-creek-incident-california-july-25-2008"],
  "07-26": ["Unfamiliar with Weather and Local Factors", "/6mfs/weather-fire-behavior/unfamiliar-weather-and-local-factors"],
  "07-27": ["Refusing Risk", "/6mfs/operational-engagement/refusing-risk"],
  "07-28": ["Stanza Fire Engine Rollover", "/6mfs/day-in-history/stanza-fire-engine-rollover-california-july-28-2002"],
  "07-29": ["Safety Zone Research", "/6mfs/operational-engagement/safety-zone-research"],
  "07-30": ["SAFENETs", "/6mfs/fire-communication/safenet"],
  "07-31": ["SAFECOMs", "/6mfs/aviation/safecoms"],
  "08-01": ["Replacing Haines LAL", "/6mfs/weather-fire-behavior/replacing-haines-index-and-lightning-activity-level"],
  "08-02": ["International Mobilization", "/6mfs/operational-engagement/international-mobilization-building-situational-awareness"],
  "08-03": ["Communicating with Aviation Resources", "/6mfs/aviation/communicating-with-aviation-resources"],
  "08-04": ["Hazard Tree Secure Felling Area", "/6mfs/felling-safety/hazard-tree-secure-felling-area"],
  "08-05": ["Mann Gulch", "/6mfs/day-in-history/mann-gulch-montana-august-5-1949"],
  "08-06": ["Subjective vs. Objective Hazards", "/6mfs/operational-engagement/subjective-vs-objective-hazards"],
  "08-07": ["Taking a Nap Near the Fireline", "/6mfs/operational-engagement/taking-nap-near-fireline"],
  "08-08": ["Contagious Diseases", "/6mfs/firefighter-health-first-aid/contagious-diseases"],
  "08-09": ["Sadler Fire", "/6mfs/day-in-history/sadler-fire-nevada-august-9-1999"],
  "08-10": ["Propane Tank Hazards", "/6mfs/misc-fireline-hazards/propane-tank-hazards"],
  "08-11": ["Wenatchee Helicopter Longline Accident", "/6mfs/day-in-history/wenatchee-helicopter-longline-accident-washington-august-11-2004"],
  "08-12": ["First Airtanker Drop – 1955, Mendocino N.F. California", "/6mfs/day-in-history/first-airtanker-drop-california-august-12-1955"],
  "08-13": ["Avoiding Fuel Geysering", "/6mfs/misc-fireline-hazards/avoiding-fuel-geysering"],
  "08-14": ["Terrain and Fuels Make Escape Difficult", "/6mfs/operational-engagement/terrain-and-fuels-make-escape-safety-zones-difficult"],
  "08-15": ["Exertional Rhabdomyolysis", "/6mfs/firefighter-health-first-aid/exertional-rhabdomyolysis"],
  "08-16": ["Illegal Grow Operations", "/6mfs/misc-fireline-hazards/illegal-grow-operations"],
  "08-17": ["Wildland/Urban Interface-Structure Protection", "/6mfs/operational-engagement/wildland-urban-interface-structure-protection"],
  "08-18": ["Properly Refuse Aviation Risk", "/6mfs/airtankers/properly-refusing-risk"],
  "08-19": ["Hazard Tree - Situational Awareness", "/6mfs/felling-safety/hazard-tree-situational-awareness"],
  "08-20": ["Great Fires of 1910 (The Big Blowup)", "/6mfs/day-in-history/great-fires-of-1910-big-blowup-august-20th"],
  "08-21": ["Parking an Engine on the Fireline", "/6mfs/vehicles-roads/parking-an-engine-fireline"],
  "08-22": ["Poisonous Plants", "/6mfs/firefighter-health-first-aid/poisonous-plants"],
  "08-23": ["Unburned Fuel Between You and the Fire", "/6mfs/operational-engagement/unburned-fuel-between-you-and-fire"],
  "08-24": ["Common Denominators of Fire Behavior on Tragedy Fires", "/6mfs/weather-fire-behavior/common-denominators-of-fire-behavior-tragedy-fires"],
  "08-25": ["Communication", "/6mfs/fire-communication/communications-lces"],
  "08-26": ["Effects of Smoke Exposure", "/6mfs/firefighter-health-first-aid/effects-of-smoke-exposure"],
  "08-27": ["Solar Farm Safety", "/6mfs/miscellaneous-fireline-hazards/solar-farm-safety"],
  "08-28": ["Attempting a Frontal Assault on a Fire", "/6mfs/operational-engagement/attempting-frontal-assault-fire"],
  "08-29": ["Type 1 Helicopter Operations", "/6mfs/aviation/type-1-helicopter-operations"],
  "08-30": ["Extreme Fire Behavior – I", "/6mfs/weather-fire-behavior/extreme-fire-behavior-i"],
  "08-31": ["Extreme Fire Behavior – II", "/6mfs/weather-fire-behavior/extreme-fire-behavior-ii"],
  "09-01": ["Sundance Fire", "/6mfs/day-in-history/sundance-fire-idaho-september-1-1967"],
  "09-02": ["Aircraft and Pilot Carding", "/6mfs/aviation/aircraft-and-pilot-carding"],
  "09-03": ["Instructions and Assignments Not Clear", "/6mfs/fire-communication/instructions-and-assignments-not-clear"],
  "09-04": ["Chainsaw Safety", "/6mfs/felling-safety/chainsaw-safety"],
  "09-05": ["Ash Pit Hazards", "/6mfs/misc-fireline-hazards/ash-pit-hazards"],
  "09-06": ["Frequent Spot Fires Across the Line", "/6mfs/weather-fire-behavior/frequent-spot-fires-across-line"],
  "09-07": ["Mental Health", "/6mfs/firefighter-health-first-aid/mental-health"],
  "09-08": ["Take 5@2 PPE", "/6mfs/firefighter-health-first-aid/take-52-ppe"],
  "09-09": ["Building Fireline Downhill With Fire Below", "/6mfs/operational-engagement/building-fireline-downhill-fire-below"],
  "09-10": ["World Suicide Prevention Day", "/6mfs/firefighter-health-first-aid/world-suicide-prevention-day-september-10"],
  "09-11": ["Bias for Action", "/6mfs/leadership/bias-for-action"],
  "09-12": ["Tuolumne Fire", "/6mfs/day-in-history/tuolumne-fire-california-september-12-2004"],
  "09-13": ["Lightning Awareness", "/6mfs/firefighter-health-first-aid/lightning-awareness"],
  "09-14": ["Aviation Communication", "/6mfs/aviation/aviation-communication"],
  "09-15": ["Falling Snags", "/6mfs/felling-safety/falling-snags"],
  "09-16": ["Entrapment Avoidance", "/6mfs/operational-engagement/entrapment-avoidance"],
  "09-17": ["Driving Safety", "/6mfs/vehicles-roads/driving-safety"],
  "09-18": ["Proper Use of Trigger Points", "/6mfs/weather-fire-behavior/proper-use-of-trigger-points"],
  "09-19": ["Stress First Aid", "/6mfs/firefighter-health-first-aid/stress-first-aid"],
  "09-20": ["Snake Bites", "/6mfs/firefighter-health-first-aid/snake-bites"],
  "09-21": ["AAR Part 1", "/6mfs/fire-communication/after-action-review-aar-part-1"],
  "09-22": ["AAR Part 2", "/6mfs/fire-communication/after-action-review-aar-part-2"],
  "09-23": ["Escape Routes 1", "/6mfs/operational-engagement/escape-routes-1"],
  "09-24": ["Escape Routes 2", "/6mfs/operational-engagement/escape-routes-2"],
  "09-25": ["Escape Routes 3", "/6mfs/operational-engagement/escape-routes-3"],
  "09-26": ["Aviation Mishap Response", "/6mfs/aviation/nwcg-aviation-mishap-response-guide-and-checklist-pms-503"],
  "09-27": ["Over the Counter Medication", "/6mfs/firefighter-health-first-aid/over-counter-medication"],
  "09-28": ["Fatigue & Stress", "/6mfs/firefighter-health-first-aid/fatigue-stress"],
  "09-29": ["Constructing Line Without a Safe Anchor Point", "/6mfs/operational-engagement/constructing-line-without-safe-anchor-point"],
  "09-30": ["Downhill Fireline Construction Checklist", "/6mfs/operational-engagement/downhill-fireline-construction-checklist"],
  "10-01": ["Bugs We Hate Part 1 - Ticks", "/6mfs/firefighter-health-first-aid/bugs-we-hate-part-1-ticks"],
  "10-02": ["Grant West RX", "/6mfs/day-in-history/grant-west-rx-california-october-2-2004"],
  "10-03": ["Hydration", "/6mfs/firefighter-health-first-aid/hydration"],
  "10-04": ["Altitude Sickness", "/6mfs/firefighter-health-first-aid/altitude-sickness"],
  "10-05": ["Fight Fire Aggressively But Provide for Safety First", "/6mfs/operational-engagement/fight-fire-aggressively-having-provided-for-safety-first"],
  "10-06": ["Aviation Watch Outs", "/6mfs/aviation/aviation-watch-outs"],
  "10-07": ["Burn Protocols", "/6mfs/firefighter-health-first-aid/burn-protocols"],
  "10-08": ["Hazard Tree - Risk Management", "/6mfs/felling-safety/hazard-tree-risk-management"],
  "10-09": ["Concussion and Head Injuries", "/6mfs/firefighter-health-first-aid/concussion-and-head-injuries"],
  "10-10": ["Firefighter Stress Management", "/6mfs/firefighter-health-first-aid/firefighter-stress-management"],
  "10-11": ["Thunderstorm Safety", "/6mfs/weather-fire-behavior/thunderstorm-safety"],
  "10-12": ["Fuel Handling", "/6mfs/misc-fireline-hazards/fuel-handling"],
  "10-13": ["Hypothermia", "/6mfs/firefighter-health-first-aid/hypothermia"],
  "10-14": ["Fire Not Scouted and Sized Up", "/6mfs/operational-engagement/fire-not-scouted-and-sized"],
  "10-15": ["Building the Team", "/6mfs/leadership/building-team"],
  "10-16": ["Helicopter Landing Area Safety", "/6mfs/aviation/helicopter-landing-area-safety"],
  "10-17": ["Operational Briefings", "/6mfs/fire-communication/operational-briefings"],
  "10-18": ["Physical Fatigue and Recovery", "/6mfs/firefighter-health-first-aid/physical-fatigue-and-recovery"],
  "10-19": ["The Pepper Hill Fire", "/6mfs/day-in-history/pepper-hill-fire-pennsylvania-october-19-1938"],
  "10-20": ["First Flight of the Huey", "/6mfs/day-in-history/first-flight-of-huey-october-20th-1956"],
  "10-21": ["Unfamiliar with Weather and Local Factors", "/6mfs/weather-fire-behavior/unfamiliar-weather-and-local-factors"],
  "10-22": ["Dozer/Plow Operations", "/6mfs/vehicles-roads/dozerplow-operations"],
  "10-23": ["Mental Health — Seeking Support", "/6mfs/firefighter-health-first-aid/mental-health-seeking-support"],
  "10-24": ["Replacing Haines LAL", "/6mfs/weather-fire-behavior/replacing-haines-index-and-lightning-activity-level"],
  "10-25": ["Hazard Tree Felling - Hang-ups", "/6mfs/felling-safety/hazard-tree-felling-hang-ups"],
  "10-26": ["Inattentive Blindness", "/6mfs/leadership/inattentive-blindness"],
  "10-27": ["Fire Shelter Deployment", "/6mfs/operational-engagement/fire-shelter-deployment"],
  "10-28": ["Fire Shelter Deployment Site Selection", "/6mfs/operational-engagement/fire-shelter-deployment-site-selection"],
  "10-29": ["Fire Shelter Stigma", "/6mfs/operational-engagement/fire-shelter-stigma"],
  "10-30": ["Hazmat Incident Operations", "/6mfs/misc-fireline-hazards/hazmat-incident-operations"],
  "10-31": ["Helicopter Performance", "/6mfs/aviation/helicopter-performance"],
  "11-01": ["Loop Fire", "/6mfs/day-in-history/loop-fire-california-november-1-1966"],
  "11-02": ["Mine Features and Hazards", "/6mfs/misc-fireline-hazards/mine-features-and-hazards"],
  "11-03": ["Solar Farm Safety", "/6mfs/miscellaneous-fireline-hazards/solar-farm-safety"],
  "11-04": ["Command Presence", "/6mfs/leadership/command-presence"],
  "11-05": ["In Country Not Seen in Daylight", "/6mfs/operational-engagement/in-country-not-seen-in-daylight"],
  "11-06": ["Hazard Tree Felling Safety Tips", "/6mfs/felling-safety/hazard-tree-felling-safety-tips"],
  "11-07": ["Mountain Flying Part 1", "/6mfs/aviation/mountain-flying-part-1"],
  "11-08": ["Mountain Flying Part 2", "/6mfs/aviation/mountain-flying-part-2"],
  "11-09": ["SAFENETs", "/6mfs/fire-communication/safenet"],
  "11-10": ["Initial Attack Sizeup/Safety", "/6mfs/operational-engagement/initial-attack-sizeupsafety"],
  "11-11": ["Veteran's Day", "/6mfs/day-in-history/veterans-day-november-11"],
  "11-12": ["Lookouts (LCES)", "/6mfs/operational-engagement/lookouts-lces"],
  "11-13": ["Base All Actions on Current and Expected Fire Behavior", "/6mfs/weather-fire-behavior/base-all-actions-current-and-expected-fire-behavior"],
  "11-14": ["Managing Vehicle Traffic in Smoke", "/6mfs/vehicles-roads/managing-vehicle-traffic-in-smoke"],
  "11-15": ["Developing a Learning Organization", "/6mfs/leadership/developing-learning-organization"],
  "11-16": ["Hydrogen Sulfide Gas", "/6mfs/firefighter-health-first-aid/hydrogen-sulfide-gas"],
  "11-17": ["On a Hillside Where Rolling Material Can Ignite Fuel Below", "/6mfs/operational-engagement/hillside-where-rolling-material-can-ignite-fuel-below"],
  "11-18": ["Refusing Risk", "/6mfs/operational-engagement/refusing-risk"],
  "11-19": ["Retardant & Water Drop Safety", "/6mfs/aviation/retardant-and-water-drop-safety"],
  "11-20": ["Bees and Wasps", "/6mfs/firefighter-health-first-aid/bees-and-wasps"],
  "11-21": ["Communication", "/6mfs/fire-communication/communications-lces"],
  "11-22": ["Hazard Tree Identification", "/6mfs/felling-safety/hazard-tree-identification"],
  "11-23": ["Powerline Safety", "/6mfs/misc-fireline-hazards/power-line-safety"],
  "11-24": ["Common Denominators of Fire Behavior on Tragedy Fires", "/6mfs/weather-fire-behavior/common-denominators-of-fire-behavior-tragedy-fires"],
  "11-25": ["Leader's Intent", "/6mfs/leadership/leaders-intent"],
  "11-26": ["Subjective vs. Objective Hazards", "/6mfs/operational-engagement/subjective-vs-objective-hazards"],
  "11-27": ["Instructions and Assignments Not Clear", "/6mfs/fire-communication/instructions-and-assignments-not-clear"],
  "11-28": ["Hypothermia", "/6mfs/firefighter-health-first-aid/hypothermia"],
  "11-29": ["SAFECOMs", "/6mfs/aviation/safecoms"],
  "11-30": ["Parking Safely on Slopes", "/6mfs/vehicles-roads/parking-safely-slopes"],
  "12-01": ["Hazard Tree Secure Felling Area", "/6mfs/felling-safety/hazard-tree-secure-felling-area"],
  "12-02": ["Five Communication Responsibilities", "/6mfs/leadership/five-communication-responsibilities"],
  "12-03": ["Safety Zone Research", "/6mfs/operational-engagement/safety-zone-research"],
  "12-04": ["Safety Zones 1 (LCES)", "/6mfs/operational-engagement/safety-zones-1-lces"],
  "12-05": ["Safety Zones 2 (LCES)", "/6mfs/operational-engagement/safety-zones-2-lces"],
  "12-06": ["Responding to Vehicle Fires", "/6mfs/vehicles-roads/responding-vehicle-fires"],
  "12-07": ["Dirty Nomex®", "/6mfs/firefighter-health-first-aid/dirty-nomexr"],
  "12-08": ["Serious Injury Procedures", "/6mfs/firefighter-health-first-aid/serious-injury-procedures"],
  "12-09": ["Working with Helicopter Drops", "/6mfs/aviation/working-helicopter-drops"],
  "12-10": ["Taking a Nap Near the Fireline", "/6mfs/operational-engagement/taking-nap-near-fireline"],
  "12-11": ["Terrain and Fuels Make Escape Difficult", "/6mfs/operational-engagement/terrain-and-fuels-make-escape-safety-zones-difficult"],
  "12-12": ["Firefighter Stress Management", "/6mfs/firefighter-health-first-aid/firefighter-stress-management"],
  "12-13": ["Transfer of Command", "/6mfs/operational-engagement/transfer-of-command"],
  "12-14": ["Peer Accountability", "/6mfs/leadership/peer-accountability"],
  "12-15": ["Frequent Spot Fires Across the Line", "/6mfs/weather-fire-behavior/frequent-spot-fires-across-line"],
  "12-16": ["Happy and Healthy Holidays", "/6mfs/firefighter-health-first-aid/happy-and-healthy-holidays"],
  "12-17": ["Carcinogen Exposure Risk", "/6mfs/firefighter-health-first-aid/carcinogen-exposure-risk"],
  "12-18": ["Roadside Incident Response", "/6mfs/vehicles-roads/roadside-incident-response"],
  "12-19": ["Aviation Watch Outs", "/6mfs/aviation/aviation-watch-outs"],
  "12-20": ["Hazard Tree - Situational Awareness", "/6mfs/felling-safety/hazard-tree-situational-awareness"],
  "12-21": ["Unburned Fuel Between You and the Fire", "/6mfs/operational-engagement/unburned-fuel-between-you-and-fire"],
  "12-22": ["Uninformed on Strategy, Tactics or Hazards", "/6mfs/operational-engagement/uninformed-strategy-tactics-or-hazards"],
  "12-23": ["Propane Tank Hazards", "/6mfs/misc-fireline-hazards/propane-tank-hazards"],
  "12-24": ["Driving Safety", "/6mfs/vehicles-roads/driving-safety"],
  "12-25": ["Vehicle Entrapment", "/6mfs/vehicles-roads/vehicle-entrapment"],
  "12-26": ["Proper Use of Trigger Points", "/6mfs/weather-fire-behavior/proper-use-of-trigger-points"],
  "12-27": ["Wildland/Urban Interface-Structure Protection", "/6mfs/operational-engagement/wildland-urban-interface-structure-protection"],
  "12-28": ["Wildland/Urban Interface Watch Outs", "/6mfs/operational-engagement/wildland-urban-interface-watch-outs"],
  "12-29": ["Leadership Environment", "/6mfs/leadership/leadership-environment"],
  "12-30": ["Unexploded Ordnance Safety", "/6mfs/misc-fireline-hazards/unexploded-ordnance-safety"],
  "12-31": ["Write Your Own 6MFS", "/6mfs/fire-communication/write-your-own-6mfs"],
};

const FALLBACK =
  "https://www.nwcg.gov/committee/6-minutes-for-safety-subcommittee#6mfscalendar";

export function sixMinutesFor(isoDate: string): SixMinutesTopic {
  const md = isoDate.slice(5, 10);
  const row = CALENDAR[md];
  if (!row) {
    return { title: "Today’s 6 Minutes for Safety", href: FALLBACK };
  }
  return { title: row[0], href: `https://www.nwcg.gov${row[1]}` };
}

